/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Hist.java
 *
 * Created on 2010-10-1, 9:54:31
 */

package plan.draw.v;

/**
 *
 * @author Administrator
 */
public class Hist extends javax.swing.JFrame {

    /** Creates new form Hist */
    public Hist() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_DropAll = new javax.swing.JButton();
        bt_DropCur = new javax.swing.JButton();
        bt_PickCur = new javax.swing.JButton();
        javax.swing.JScrollPane jsp1 = new javax.swing.JScrollPane();
        ls_HistList = new javax.swing.JList();
        javax.swing.JScrollPane jsp2 = new javax.swing.JScrollPane();
        ta_HistInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_DropAll.setText("删除所有");
        bt_DropAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_DropAllActionPerformed(evt);
            }
        });

        bt_DropCur.setText("删除当前");
        bt_DropCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_DropCurActionPerformed(evt);
            }
        });

        bt_PickCur.setText("恢复当前");
        bt_PickCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_PickCurActionPerformed(evt);
            }
        });

        ls_HistList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "2010-06-19 15:17:21", "2010-06-19 15:17:21", "2010-06-19 15:17:21", "2010-06-19 15:17:21", "2010-06-19 15:17:21", "2010-06-19 15:17:21" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ls_HistList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ls_HistListValueChanged(evt);
            }
        });
        jsp1.setViewportView(ls_HistList);

        ta_HistInfo.setColumns(20);
        ta_HistInfo.setRows(5);
        jsp2.setViewportView(ta_HistInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_PickCur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_DropCur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_DropAll))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jsp1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jsp2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsp2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(jsp1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_DropAll)
                    .addComponent(bt_DropCur)
                    .addComponent(bt_PickCur))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_DropAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_DropAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_DropAllActionPerformed

    private void bt_DropCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_DropCurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_DropCurActionPerformed

    private void bt_PickCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_PickCurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_PickCurActionPerformed

    private void ls_HistListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ls_HistListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ls_HistListValueChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_DropAll;
    private javax.swing.JButton bt_DropCur;
    private javax.swing.JButton bt_PickCur;
    private javax.swing.JList ls_HistList;
    private javax.swing.JTextArea ta_HistInfo;
    // End of variables declaration//GEN-END:variables

}
