/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Icon.java
 *
 * Created on 2010-3-5, 12:57:12
 */

package draw.v;

/**
 *
 * @author Administrator
 */
public class Icon extends javax.swing.JPanel {

    /** Creates new form Icon */
    public Icon() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_Append = new javax.swing.JButton();
        bt_Select = new javax.swing.JButton();
        javax.swing.JScrollPane sp_IconGrid = new javax.swing.JScrollPane();
        tb_IconGrid = new javax.swing.JTable();

        bt_Append.setText("A");

        bt_Select.setText("S");

        tb_IconGrid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_IconGrid.setCellSelectionEnabled(true);
        tb_IconGrid.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_IconGrid.setShowHorizontalLines(false);
        tb_IconGrid.setShowVerticalLines(false);
        sp_IconGrid.setViewportView(tb_IconGrid);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sp_IconGrid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_Select)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Append)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sp_IconGrid, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Append)
                    .addComponent(bt_Select))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Append;
    private javax.swing.JButton bt_Select;
    private javax.swing.JTable tb_IconGrid;
    // End of variables declaration//GEN-END:variables

}
