/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InfoProp.java
 *
 * Created on 2009-10-28, 9:23:25
 */

package test.draw.p;

/**
 *
 * @author Amon
 */
public class InfoProp extends javax.swing.JPanel {

    /** Creates new form InfoProp */
    public InfoProp() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lt_Soft = new javax.swing.JLabel();
        lc_Soft = new javax.swing.JLabel();
        lt_Vers = new javax.swing.JLabel();
        lc_Vers = new javax.swing.JLabel();
        lt_Site = new javax.swing.JLabel();
        lc_Site = new javax.swing.JLabel();
        lt_Copy = new javax.swing.JLabel();
        lc_Copy = new javax.swing.JLabel();
        javax.swing.JScrollPane sp = new javax.swing.JScrollPane();
        ta_Note = new javax.swing.JTextArea();

        lt_Soft.setText("软件：");

        lc_Soft.setText("jLabel2");

        lt_Vers.setText("版本：");

        lc_Vers.setText("jLabel4");

        lt_Site.setText("首页：");

        lc_Site.setForeground(new java.awt.Color(0, 0, 255));
        lc_Site.setText("jLabel6");
        lc_Site.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lc_SiteMouseReleased(evt);
            }
        });

        lt_Copy.setText("版权：");

        lc_Copy.setText("jLabel8");

        ta_Note.setColumns(20);
        ta_Note.setEditable(false);
        ta_Note.setRows(5);
        sp.setViewportView(ta_Note);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lt_Site)
                    .addComponent(lt_Copy)
                    .addComponent(lt_Vers)
                    .addComponent(lt_Soft))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lc_Soft)
                    .addComponent(lc_Vers)
                    .addComponent(lc_Site)
                    .addComponent(lc_Copy))
                .addContainerGap(250, Short.MAX_VALUE))
            .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lt_Soft)
                    .addComponent(lc_Soft))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lt_Vers)
                    .addComponent(lc_Vers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lt_Site)
                    .addComponent(lc_Site))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lt_Copy)
                    .addComponent(lc_Copy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lc_SiteMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lc_SiteMouseReleased
    {//GEN-HEADEREND:event_lc_SiteMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lc_SiteMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lc_Copy;
    private javax.swing.JLabel lc_Site;
    private javax.swing.JLabel lc_Soft;
    private javax.swing.JLabel lc_Vers;
    private javax.swing.JLabel lt_Copy;
    private javax.swing.JLabel lt_Site;
    private javax.swing.JLabel lt_Soft;
    private javax.swing.JLabel lt_Vers;
    private javax.swing.JTextArea ta_Note;
    // End of variables declaration//GEN-END:variables

}
