/*
 *  Copyright (C) 2011 Aven
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * TpltDialog.java
 *
 * Created on 2011-5-8, 9:58:54
 */

package dev.x.mexp;

/**
 *
 * @author Aven
 */
public class TpltDialog extends javax.swing.JDialog {

    /** Creates new form TpltDialog */
    public TpltDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        btSaveDat = new javax.swing.JButton();
        btNewType = new javax.swing.JButton();
        btNewProp = new javax.swing.JButton();
        lb_TpltKind = new javax.swing.JLabel();
        cb_TpltKind = new javax.swing.JComboBox();
        lb_TpltName = new javax.swing.JLabel();
        tf_TpltName = new javax.swing.JTextField();
        lb_TpltData = new javax.swing.JLabel();
        tf_TpltData = new javax.swing.JTextField();
        lb_TpltDesp = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_TpltDesp = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(jTree1);

        btSaveDat.setText("保存(S)");
        btSaveDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveDatActionPerformed(evt);
            }
        });

        btNewType.setText("新增类别(K)");
        btNewType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewTypeActionPerformed(evt);
            }
        });

        btNewProp.setText("新增属性(P)");
        btNewProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewPropActionPerformed(evt);
            }
        });

        lb_TpltKind.setLabelFor(cb_TpltKind);
        lb_TpltKind.setText("属性类型(T)");

        cb_TpltKind.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_TpltKind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_TpltKindActionPerformed(evt);
            }
        });

        lb_TpltName.setLabelFor(tf_TpltName);
        lb_TpltName.setText("属性名称(N)");

        tf_TpltName.setText("jTextField1");

        lb_TpltData.setLabelFor(tf_TpltData);
        lb_TpltData.setText("默认数据(D)");

        tf_TpltData.setText("jTextField2");

        lb_TpltDesp.setLabelFor(ta_TpltDesp);
        lb_TpltDesp.setText("备注(M)");

        ta_TpltDesp.setColumns(20);
        ta_TpltDesp.setRows(5);
        jScrollPane2.setViewportView(ta_TpltDesp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btNewProp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNewType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSaveDat))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_TpltKind, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_TpltName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_TpltData, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_TpltDesp, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_TpltKind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_TpltName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_TpltData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_TpltKind)
                            .addComponent(cb_TpltKind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_TpltName)
                            .addComponent(tf_TpltName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_TpltData)
                            .addComponent(tf_TpltData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_TpltDesp)
                                .addGap(91, 91, 91))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSaveDat)
                    .addComponent(btNewType)
                    .addComponent(btNewProp))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNewPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewPropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btNewPropActionPerformed

    private void btNewTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btNewTypeActionPerformed

    private void btSaveDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveDatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSaveDatActionPerformed

    private void cb_TpltKindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_TpltKindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_TpltKindActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TpltDialog dialog = new TpltDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNewProp;
    private javax.swing.JButton btNewType;
    private javax.swing.JButton btSaveDat;
    private javax.swing.JComboBox cb_TpltKind;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lb_TpltData;
    private javax.swing.JLabel lb_TpltDesp;
    private javax.swing.JLabel lb_TpltKind;
    private javax.swing.JLabel lb_TpltName;
    private javax.swing.JTextArea ta_TpltDesp;
    private javax.swing.JTextField tf_TpltData;
    private javax.swing.JTextField tf_TpltName;
    // End of variables declaration//GEN-END:variables

}
