/*
 * Form.java
 *
 * Created on 2009-11-7, 9:46:10
 */

package test;

/**
 *
 * @author Amon
 */
public class Form extends javax.swing.JPanel {

    /** Creates new form Form */
    public Form() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_UserName = new javax.swing.JLabel();
        tf_UserName = new javax.swing.JTextField();
        lb_UserKey0 = new javax.swing.JLabel();
        pf_UserKey0 = new javax.swing.JPasswordField();
        lb_UserKey1 = new javax.swing.JLabel();
        pf_UserKey1 = new javax.swing.JPasswordField();
        lb_UserKey2 = new javax.swing.JLabel();
        pf_UserKey2 = new javax.swing.JPasswordField();

        lb_UserName.setText("用户：");

        tf_UserName.setColumns(16);
        tf_UserName.setText("jTextField1");
        tf_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_UserNameActionPerformed(evt);
            }
        });

        lb_UserKey0.setText("口令：");

        pf_UserKey0.setColumns(16);
        pf_UserKey0.setText("jPasswordField1");
        pf_UserKey0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_UserKey0ActionPerformed(evt);
            }
        });

        lb_UserKey1.setText("新口令：");

        pf_UserKey1.setColumns(16);
        pf_UserKey1.setText("jPasswordField2");
        pf_UserKey1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_UserKey1ActionPerformed(evt);
            }
        });

        lb_UserKey2.setText("口令确认：");

        pf_UserKey2.setColumns(16);
        pf_UserKey2.setText("jPasswordField1");
        pf_UserKey2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_UserKey2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_UserKey0, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_UserName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_UserKey1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_UserKey2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pf_UserKey0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pf_UserKey1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pf_UserKey2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_UserName)
                    .addComponent(tf_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_UserKey0)
                    .addComponent(pf_UserKey0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_UserKey1)
                    .addComponent(pf_UserKey1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_UserKey2)
                    .addComponent(pf_UserKey2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_UserNameActionPerformed

    private void pf_UserKey0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_UserKey0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_UserKey0ActionPerformed

    private void pf_UserKey1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_UserKey1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_UserKey1ActionPerformed

    private void pf_UserKey2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_UserKey2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_UserKey2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_UserKey0;
    private javax.swing.JLabel lb_UserKey1;
    private javax.swing.JLabel lb_UserKey2;
    private javax.swing.JLabel lb_UserName;
    private javax.swing.JPasswordField pf_UserKey0;
    private javax.swing.JPasswordField pf_UserKey1;
    private javax.swing.JPasswordField pf_UserKey2;
    private javax.swing.JTextField tf_UserName;
    // End of variables declaration//GEN-END:variables

}
