/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Body.java
 *
 * Created on 2010-1-29, 13:21:45
 */

package test.draw.v;

/**
 *
 * @author Administrator
 */
public class Body extends javax.swing.JPanel {

    /** Creates new form Body */
    public Body() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_MailHead = new javax.swing.JLabel();
        lb_MailUser = new javax.swing.JLabel();
        tf_MailHead = new javax.swing.JTextField();
        tf_MailUser = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_MailBody = new javax.swing.JTextArea();

        lb_MailHead.setText("jLabel111111");

        lb_MailUser.setText("jLabel2");

        tf_MailHead.setText("jTextField1");

        tf_MailUser.setText("jTextField2");

        ta_MailBody.setColumns(20);
        ta_MailBody.setRows(5);
        jScrollPane1.setViewportView(ta_MailBody);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_MailUser)
                    .addComponent(lb_MailHead))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_MailHead, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(tf_MailUser, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_MailHead)
                    .addComponent(tf_MailHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_MailUser)
                    .addComponent(tf_MailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_MailHead;
    private javax.swing.JLabel lb_MailUser;
    private javax.swing.JTextArea ta_MailBody;
    private javax.swing.JTextField tf_MailHead;
    private javax.swing.JTextField tf_MailUser;
    // End of variables declaration//GEN-END:variables

}
