/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Mail.java
 *
 * Created on 2010-1-29, 11:45:00
 */

package test.draw.v;

/**
 *
 * @author Amon
 */
public class Mail extends javax.swing.JPanel {

    /** Creates new form Mail */
    public Mail() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JSplitPane sp1 = new javax.swing.JSplitPane();
        javax.swing.JSplitPane sp2 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tr_MailBoxs = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_MailMsgs = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_MailBody = new javax.swing.JTextArea();
        load1 = new test.draw.v.Load();

        sp1.setDividerLocation(120);
        sp1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        sp1.setOneTouchExpandable(true);

        sp2.setDividerLocation(120);
        sp2.setOneTouchExpandable(true);

        jScrollPane1.setViewportView(tr_MailBoxs);

        sp2.setLeftComponent(jScrollPane1);

        tb_MailMsgs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb_MailMsgs);

        sp2.setRightComponent(jScrollPane2);

        sp1.setTopComponent(sp2);

        ta_MailBody.setColumns(20);
        ta_MailBody.setRows(5);
        jScrollPane3.setViewportView(ta_MailBody);

        sp1.setRightComponent(jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(load1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sp1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(load1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private test.draw.v.Load load1;
    private javax.swing.JTextArea ta_MailBody;
    private javax.swing.JTable tb_MailMsgs;
    private javax.swing.JTree tr_MailBoxs;
    // End of variables declaration//GEN-END:variables

}
