/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * User.java
 *
 * Created on 2010-5-22, 8:32:06
 */

package test.draw.v;

/**
 *
 * @author Awen
 */
public class User extends javax.swing.JPanel {

    /** Creates new form User */
    public User() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pl_GuidPane = new javax.swing.JPanel();
        pl_InfoPane = new javax.swing.JPanel();
        pl_SafePane = new javax.swing.JPanel();
        bt_Cancel = new javax.swing.JButton();
        bt_Confrm = new javax.swing.JButton();
        lb_UsrLabel = new javax.swing.JLabel();
        lb_KeyLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout pl_GuidPaneLayout = new javax.swing.GroupLayout(pl_GuidPane);
        pl_GuidPane.setLayout(pl_GuidPaneLayout);
        pl_GuidPaneLayout.setHorizontalGroup(
            pl_GuidPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );
        pl_GuidPaneLayout.setVerticalGroup(
            pl_GuidPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pl_InfoPaneLayout = new javax.swing.GroupLayout(pl_InfoPane);
        pl_InfoPane.setLayout(pl_InfoPaneLayout);
        pl_InfoPaneLayout.setHorizontalGroup(
            pl_InfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );
        pl_InfoPaneLayout.setVerticalGroup(
            pl_InfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pl_SafePaneLayout = new javax.swing.GroupLayout(pl_SafePane);
        pl_SafePane.setLayout(pl_SafePaneLayout);
        pl_SafePaneLayout.setHorizontalGroup(
            pl_SafePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pl_SafePaneLayout.setVerticalGroup(
            pl_SafePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        bt_Cancel.setText("jButton1");

        bt_Confrm.setText("jButton2");

        lb_UsrLabel.setText("jLabel1");

        lb_KeyLabel.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pl_SafePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lb_UsrLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_KeyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(bt_Confrm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Cancel))
                    .addComponent(pl_GuidPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pl_InfoPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pl_GuidPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pl_InfoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pl_SafePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Cancel)
                    .addComponent(bt_Confrm)
                    .addComponent(lb_UsrLabel)
                    .addComponent(lb_KeyLabel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Cancel;
    private javax.swing.JButton bt_Confrm;
    private javax.swing.JLabel lb_KeyLabel;
    private javax.swing.JLabel lb_UsrLabel;
    private javax.swing.JPanel pl_GuidPane;
    private javax.swing.JPanel pl_InfoPane;
    private javax.swing.JPanel pl_SafePane;
    // End of variables declaration//GEN-END:variables

}
