/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Wait.java
 *
 * Created on 2010-5-23, 11:26:56
 */

package test.draw.v;

/**
 *
 * @author Awen
 */
public class Wait extends javax.swing.JFrame {

    /** Creates new form Wait */
    public Wait() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_BusyIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_BusyIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_BusyIcon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lb_BusyIcon, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wait().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_BusyIcon;
    // End of variables declaration//GEN-END:variables

}
