/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditProp.java
 *
 * Created on 2010-3-6, 12:02:17
 */

package draw.p;

/**
 *
 * @author Amon
 */
public class EditProp extends javax.swing.JPanel {

    /** Creates new form EditProp */
    public EditProp() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_CharTplt = new javax.swing.JLabel();
        cb_CharTplt = new javax.swing.JComboBox();
        lb_CharName = new javax.swing.JLabel();
        tf_CharName = new javax.swing.JTextField();
        lb_CharTips = new javax.swing.JLabel();
        tf_CharTips = new javax.swing.JTextField();
        lb_CharSets = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_CharSets = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();

        lb_CharTplt.setLabelFor(cb_CharTplt);
        lb_CharTplt.setText("四信中文");

        cb_CharTplt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_CharTplt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CharTpltActionPerformed(evt);
            }
        });

        lb_CharName.setLabelFor(tf_CharName);
        lb_CharName.setText("jLabel2");

        tf_CharName.setText("jTextField1");

        lb_CharTips.setLabelFor(tf_CharTips);
        lb_CharTips.setText("jLabel3");

        tf_CharTips.setText("jTextField2");

        lb_CharSets.setLabelFor(ta_CharSets);
        lb_CharSets.setText("jLabel4");

        ta_CharSets.setColumns(20);
        ta_CharSets.setRows(5);
        jScrollPane1.setViewportView(ta_CharSets);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_CharSets)
                    .addComponent(lb_CharTips)
                    .addComponent(lb_CharName)
                    .addComponent(lb_CharTplt)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_CharTplt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_CharName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_CharTips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_CharTplt)
                    .addComponent(cb_CharTplt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_CharName)
                    .addComponent(tf_CharName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_CharTips)
                    .addComponent(tf_CharTips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_CharSets)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cb_CharTpltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CharTpltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_CharTpltActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_CharTplt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_CharName;
    private javax.swing.JLabel lb_CharSets;
    private javax.swing.JLabel lb_CharTips;
    private javax.swing.JLabel lb_CharTplt;
    private javax.swing.JTextArea ta_CharSets;
    private javax.swing.JTextField tf_CharName;
    private javax.swing.JTextField tf_CharTips;
    // End of variables declaration//GEN-END:variables

}
