/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ucfg.java
 *
 * Created on 2010-2-27, 10:42:07
 */

package draw.p;

/**
 *
 * @author Amon
 */
public class Ucfg extends javax.swing.JPanel {

    /** Creates new form Ucfg */
    public Ucfg() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane sp_PropList = new javax.swing.JScrollPane();
        ls_PropList = new javax.swing.JList();
        pl_CardPanel = new javax.swing.JPanel();
        bt_Discard = new javax.swing.JButton();
        bt_Confirm = new javax.swing.JButton();
        lb_HeadPanel = new javax.swing.JLabel();
        bt_Applied = new javax.swing.JButton();

        ls_PropList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "关于作者", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        sp_PropList.setViewportView(ls_PropList);

        javax.swing.GroupLayout pl_CardPanelLayout = new javax.swing.GroupLayout(pl_CardPanel);
        pl_CardPanel.setLayout(pl_CardPanelLayout);
        pl_CardPanelLayout.setHorizontalGroup(
            pl_CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        pl_CardPanelLayout.setVerticalGroup(
            pl_CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        bt_Discard.setText("jButton1");

        bt_Confirm.setText("jButton2");

        lb_HeadPanel.setText("jLabel1");

        bt_Applied.setText("jButton1");
        bt_Applied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AppliedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sp_PropList, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pl_CardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_HeadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_Applied)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Confirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Discard)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sp_PropList, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lb_HeadPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pl_CardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Discard)
                    .addComponent(bt_Confirm)
                    .addComponent(bt_Applied))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_AppliedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AppliedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_AppliedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Applied;
    private javax.swing.JButton bt_Confirm;
    private javax.swing.JButton bt_Discard;
    private javax.swing.JLabel lb_HeadPanel;
    private javax.swing.JList ls_PropList;
    private javax.swing.JPanel pl_CardPanel;
    // End of variables declaration//GEN-END:variables

}
